export const personas=['Change Manager','AI Change Manager','Instructional Designer','Operations / Business Development'];
export const outcomes=['not submitted','submission unconfirmed','submitted','interviewing','offer','rejected','withdrawn','role filled','closed'];
export const growthStages=['recommended','saved','planned','registered','in progress','completed','skipped'];
export function day(value){if(!value)return null;const d=String(value).slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(d)?Date.parse(d+'T12:00:00Z'):null}
export function noResponse(r,now=new Date(),threshold=14){return !!(r.confirmed&&r.submitted&&!r.humanResponse&&!['rejected','withdrawn','offer','role filled','closed'].includes(r.outcome)&&day(r.submitted)!==null&&(now.getTime()-day(r.submitted))/86400000>=threshold)}
export function summary(rows,now=new Date(),threshold=14){const submitted=rows.filter(r=>r.confirmed);return {total:rows.length,confirmed:submitted.length,unconfirmed:rows.filter(r=>r.outcome==='submission unconfirmed').length,interviews:rows.filter(r=>r.outcome==='interviewing').length,offers:rows.filter(r=>r.outcome==='offer').length,rejected:rows.filter(r=>r.outcome==='rejected').length,noResponse:rows.filter(r=>noResponse(r,now,threshold)).length,humanResponses:submitted.filter(r=>r.humanResponse).length,rate:submitted.length?submitted.filter(r=>r.humanResponse).length/submitted.length:null}}
export function validateMission(r){if(!r.company?.trim()||!r.title?.trim())throw new Error('Company and role are required.');if(!outcomes.includes(r.outcome))throw new Error('Choose a valid outcome.');if(r.confirmed&&(!r.evidence?.trim()||!r.submitted))throw new Error('A confirmed submission needs an evidence URL and submission date.');if(r.confirmed&&['not submitted','submission unconfirmed'].includes(r.outcome))throw new Error('Unsubmitted or unconfirmed records cannot count as confirmed.');for(const k of ['evidence','posting','portfolio'])if(r[k]&&!safeURL(r[k]))throw new Error('Use a complete https:// or http:// URL.');return r}
export function safeURL(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null}catch{return null}}
export function routeCommand(input,rows=[]){const q=input.trim().toLowerCase();if(q.startsWith('note:'))return {type:'note',text:input.trim().slice(5).trim()};if(q.includes('unconfirmed'))return {route:'missions?filter=unconfirmed',text:'Showing applications whose submission is not confirmed.'};if(q.includes('overdue')||q.includes('follow-up'))return {route:'missions?filter=followups',text:'Showing follow-ups at or beyond your response threshold.'};for(const x of ['missions','signal','results','portfolios','evidence','intelligence','memory','growth','settings','command'])if(q===x||q.startsWith('open '+x)||q.includes('show '+x))return {route:x,text:'Opening '+x+'.'};const match=rows.find(r=>q==='open '+r.company.toLowerCase());if(match)return {route:'missions/'+match.id,text:'Opening '+match.company+'.'};if(q.includes('storyline'))return {route:'evidence',text:'Opening career evidence. Demo evidence is synthetic.'};return {text:'Try “open missions”, “show overdue follow-ups”, “show unconfirmed applications”, “show growth opportunities”, or “note: …”. AI conversation is not connected.'}}
export function upsertMessage(messages,message){return messages.some(m=>m.id===message.id)?messages:[...messages,message]}
export function safeText(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
