import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {timingSafeEqual} from 'node:crypto';
const root=resolve(process.env.NEXUS_PUBLIC_DIR||'.');
const allowed=new Set(['/index.html','/style.css','/app.js','/model.js','/demo.js','/store.js']);
const config=()=>({token:process.env.NOTION_TOKEN,missions:process.env.NOTION_MISSIONS_SOURCE,contacts:process.env.NOTION_CONTACTS_SOURCE,password:process.env.NEXUS_PASSWORD});
function authorized(req){const c=config();if(!c.password||c.password.length<24)return false;const expected=Buffer.from('Basic '+Buffer.from('nexus:'+c.password).toString('base64')),given=Buffer.from(req.headers.authorization||'');return expected.length===given.length&&timingSafeEqual(expected,given)}
async function notionQuery(source){if(!/^[0-9a-f-]{32,36}$/i.test(source||''))throw new Error('Notion data source is not configured.');let rows=[],cursor;do{const response=await fetch('https://api.notion.com/v1/data_sources/'+source+'/query',{method:'POST',headers:{Authorization:'Bearer '+config().token,'Notion-Version':'2025-09-03','Content-Type':'application/json'},body:JSON.stringify({page_size:100,...(cursor?{start_cursor:cursor}:{})}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('Notion request failed ('+response.status+'). Check server-side access.');const payload=await response.json();rows.push(...payload.results);cursor=payload.has_more?payload.next_cursor:null;if(rows.length>5000)throw new Error('Workspace exceeds this release’s 5,000-record safety limit.');}while(cursor);return rows}
function text(p){if(!p)return '';if(p.type==='title'||p.type==='rich_text')return (p[p.type]||[]).map(x=>x.plain_text||x.text?.content||'').join('');if(p.type==='select')return p.select?.name||'';if(p.type==='date')return p.date?.start||'';if(p.type==='checkbox')return p.checkbox;return p[p.type]||''}
function mission(p){const v=k=>text(p.properties[k]);const signal=v('Signal'),confirmed=v('Confirmed submission')===true,stage=v('Stage');let outcome=confirmed?'submitted':'not submitted';if(signal==='Rejected')outcome='rejected';else if(signal==='Offer'||stage==='Offer')outcome='offer';else if(signal==='Interview'||stage==='Interview')outcome='interviewing';else if(stage==='Blocked')outcome='submission unconfirmed';return {id:p.id,company:v('Employer'),title:v('Mission'),persona:({'AI adoption':'AI Change Manager','Change strategy':'Change Manager','Instructional design':'Instructional Designer','Continuous improvement':'Operations / Business Development'})[v('Positioning')]||v('Positioning'),outcome,confirmed,submitted:v('Submitted'),humanResponse:v('Last human response'),evidence:v('Evidence'),posting:v('Posting'),portfolio:v('Portfolio'),resume:v('Resume version'),cover:v('Cover letter'),blocker:v('Blocker'),nextAction:v('Next action'),review:v('Next review'),requisition:v('Requisition'),signal,notionURL:p.url,updatedAt:p.last_edited_time,history:[]}}
function contact(p){const v=k=>text(p.properties[k]);return {id:p.id,name:v('Contact'),company:v('Organization'),role:v('Role'),identity:v('Identity'),next:v('Next action'),status:v('Message status'),linkedin:v('LinkedIn'),notionURL:p.url}}
export function createServer(){return http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; connect-src 'self'; img-src 'self' data:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");const json=(status,value)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(value))};if(req.method!=='GET')return json(405,{error:'This release exposes read-only private snapshots. Writes are not enabled.'});if(url.pathname.startsWith('/api/')){const c=config();if(!c.token||!c.password||c.password.length<24)return json(503,{error:'Private server is not configured. No private data is available.'});if(!authorized(req)){res.setHeader('WWW-Authenticate','Basic realm="NEXUS private workspace", charset="UTF-8"');return json(401,{error:'Authentication required.'})}if(url.pathname!=='/api/workspace')return json(404,{error:'Unknown API route.'});try{const missions=await notionQuery(c.missions);const contacts=c.contacts?await notionQuery(c.contacts):[];return json(200,{mode:'private',missions:missions.map(mission),contacts:contacts.map(contact),syncedAt:new Date().toISOString()})}catch(error){return json(502,{error:error.message})}}const pathname=url.pathname==='/'?'/index.html':url.pathname;if(!allowed.has(pathname))return json(404,{error:'Not found'});try{const body=await readFile(resolve(root,'.'+pathname));res.writeHead(200,{'Content-Type':({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'})[extname(pathname)]});res.end(body)}catch{json(404,{error:'Not found'})}})}
if(process.argv[1]&&resolve(process.argv[1])===resolve(new URL(import.meta.url).pathname)){createServer().listen(Number(process.env.PORT||3000),process.env.HOST||'127.0.0.1',()=>console.log('NEXUS running. Private API is read-only and requires configured server credentials.'))}
